[package]
name = "http"
version = "0.1.2"
authors = ["merl <merl.001.mia@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { git = "https://github.com/merl-twin/hyper.git", branch = "0.11.27" }

futures = "0.1"
tokio-core = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
