[package]
name = "http"
version = "0.1.0"
authors = ["merl <merl.001.mia@gmail.com>"]

[dependencies]
hyper = { git = "https://github.com/merl-twin/hyper.git", branch = "0.11.27" }

tokio-core = "0.1"
futures = "0.1"
time = "0.1"
clap = "2.31"
env_logger = "0.5"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
